image: registry.icg360.net/deploy:latest

services:
  - docker:dind

stages:
  - build
  - docker
  - deploy

variables:
  IMAGE_NAME: eng-growth

before_script:
  - |
    if [[ "${CI_COMMIT_TAG}" != "" ]]; then PREFIX="${CI_COMMIT_TAG}-"; fi
    export VERSION="${PREFIX}${CI_COMMIT_SHA:0:8}"
    echo "VERSION: ${VERSION}"

eng-growth-ui:build:
  image: node:13
  stage: build
  only:
    refs:
      - tags
      - master
  script:
    - npm install -g yarn
    - yarn
    - yarn export
    - tar -czf build-ui.tar --exclude='backend/' --exclude='docker/' --exclude='*.tar' .
  artifacts:
    paths:
      - build-ui.tar
    expire_in: 1 week

eng-growth-ui:docker:
  image: docker:git
  stage: docker
  only:
    refs:
      - tags
      - master
  script:
    - docker login -u devops -p $DOCKER_REGISTRY_SECRET registry.icg360.net
    - docker build --network host -t registry.icg360.net$IMAGE_NAME:$VERSION docker
    - docker tag registry.icg360.net/$IMAGE_NAME:${VERSION} registry.icg360.net/$IMAGE_NAME:latest
    - docker push registry.icg360.net/$IMAGE_NAME:${VERSION}
    - docker push registry.icg360.net/$IMAGE_NAME:latest

eng-growth-backend:docker:
  image: docker:git
  stage: docker
  only:
    refs:
      - tags
      - master
  script:
    - docker login -u devops -p $DOCKER_REGISTRY_SECRET registry.icg360.net
    - docker build --network host -t registry.icg360.net$IMAGE_NAME-backend:$VERSION docker
    - docker tag registry.icg360.net/$IMAGE_NAME-backend:${VERSION} registry.icg360.net/$IMAGE_NAME-backend:latest
    - docker push registry.icg360.net/$IMAGE_NAME-backend:${VERSION}
    - docker push registry.icg360.net/$IMAGE_NAME-backend:latest

ui-infra:
  stage: deploy
  when: manual
  only:
    - master
    - tags
  environment:
    name: infra
  script:
    - rancher-deploy -e infra -s eng-growth ${VERSION}

backend-infra:
  stage: deploy
  when: manual
  only:
    - master
    - tags
  environment:
    name: infra
  script:
    - rancher-deploy -e infra -s eng-growth-backend ${VERSION}